name: Build and Deploy to ECS
 
on:
  pull_request:
    branches: ['main']
      
env:
  DOCKER_FILE_BE: Dockerfile

jobs:
# Build and push a Docker image for BE to ECR
  BE:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{env.DOCKER_FILE_BE}}
          push: false
          tags: |
            ${{ secrets.ECR_REPOSITORY_URI }}:latest
            ${{ secrets.ECR_REPOSITORY_URI }}:dev-${{ github.sha }}
