name: Build and Push

on:
  pull_request:
    branches: ['main']

jobs:
  build_backend:
    uses: ./.github/workflows/Reusable.yml
    with:
      dockerfile_path: Dockerfile
      aws_region: us-east-1
    secrets:
      ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
